"""
Defines the shared typed state and structured schemas for MarketSentry.
Includes resilient pre-validators for local LLM output normalization.
"""
from typing import Annotated, List, Optional, Literal, Any
from typing_extensions import TypedDict
from pydantic import BaseModel, Field, field_validator
import operator


def _normalize_score(val: Any) -> float:
    """Safely converts arbitrary model score formats (e.g. 9, 90, 0.9, '0.85') to a 0.0 - 1.0 float."""
    try:
        numeric = float(val)
        if numeric > 10.0:
            numeric = numeric / 100.0  # Normalized from 0-100 scale
        elif numeric > 1.0:
            numeric = numeric / 10.0   # Normalized from 0-10 scale
        return max(0.0, min(1.0, round(numeric, 2)))
    except (ValueError, TypeError):
        return 0.75  # Fallback default score


# ---------------------------------------------------------------------------
# Structured LLM Output Schemas (Pydantic V2)
# ---------------------------------------------------------------------------

class ThesisPoint(BaseModel):
    point: str = Field(description="Summary of the argument.")
    metric_or_citation: str = Field(description="Concrete numeric metric or 10-K filing citation supporting the point.")
    confidence_score: float = Field(description="Confidence score normalized between 0.0 and 1.0.")

    @field_validator("confidence_score", mode="before")
    @classmethod
    def parse_confidence(cls, v: Any) -> float:
        return _normalize_score(v)


class AgentThesis(BaseModel):
    stance: Literal["BULL", "BEAR"] = Field(description="Stance taken: BULL or BEAR.")
    summary: str = Field(description="Executive thesis paragraph.")
    key_points: List[ThesisPoint] = Field(description="List of evidence-backed claims.")


class AuditCritique(BaseModel):
    target_stance: Literal["BULL", "BEAR"] = Field(default="BULL", description="Target stance reviewed.")
    unsubstantiated_claims: List[str] = Field(default_factory=list, description="Specific claims lacking empirical evidence.")
    passes_audit: bool = Field(default=True, description="True if claims are verified by data; False if ungrounded.")


class FinalInvestmentMemo(BaseModel):
    ticker: str
    verdict: Literal["OVERWEIGHT", "NEUTRAL", "UNDERWEIGHT"]
    conviction_score: float = Field(description="Risk-adjusted conviction score between 0.0 and 1.0.")
    primary_catalyst: str = Field(description="Strongest growth catalyst from Bull debate.")
    primary_risk: str = Field(description="Deadliest risk vector from Bear debate.")
    synthesis_memo: str = Field(description="Comprehensive final memo explaining the institutional decision.")

    @field_validator("conviction_score", mode="before")
    @classmethod
    def parse_conviction(cls, v: Any) -> float:
        return _normalize_score(v)


# ---------------------------------------------------------------------------
# LangGraph Graph State
# ---------------------------------------------------------------------------

class MarketGraphState(TypedDict):
    """
    Central graph state for MarketSentry.
    Annotated reducers (e.g. operator.add) allow appending audit logs cleanly.
    """
    ticker: str
    raw_market_data: str
    raw_sec_data: str
    
    # Structured outputs from specialized nodes
    bull_thesis: Optional[AgentThesis]
    bear_thesis: Optional[AgentThesis]
    
    # Audit trail: uses operator.add to append critique events across rounds
    audit_history: Annotated[List[AuditCritique], operator.add]
    
    # Loop controller flags
    audit_round: int
    is_audit_approved: bool
    
    # Final trade memo generated by the Arbiter
    final_memo: Optional[FinalInvestmentMemo]